In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt
import cv2

In [2]:
import os

In [3]:
os.listdir()

['logs',
 '.git',
 'preprocess.py',
 'make_predictions.py',
 'model.py',
 'README.md',
 'data',
 'experiments.ipynb',
 'train.py',
 '.ipynb_checkpoints',
 'loss.py',
 'HNet.py',
 'clustering.py']

In [4]:
os.listdir('./data')

['cluster', 'train_binary']

In [9]:
a=cv2.imread(os.path.join('./data/cluster',os.listdir('./data/cluster')[0]),cv2.IMREAD_UNCHANGED)

In [10]:
a.shape

(720, 1280)

In [11]:
a=torch.tensor(a)

In [12]:
a

tensor([[   0,    0,    0,  ...,    0,    0,    0],
        [   0,    0,    0,  ...,    0,    0,    0],
        [   0,    0,    0,  ...,    0,    0,    0],
        ...,
        [   0,    0,    0,  ...,    0,    0,    0],
        [   0,    0,    0,  ...,    0,    0,    0],
        [   0,    0,    0,  ...,    0,    0,    0]], dtype=torch.uint8)

In [13]:
b=torch.ones_like(a)

In [16]:
c=torch.stack([a,b])

In [17]:
c.size()

torch.Size([2, 720, 1280])

In [18]:
a.unique()

tensor([ 155,  205,  255,    0], dtype=torch.uint8)

In [19]:
mask=a.eq(255)

In [20]:
mask

tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        ...,
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0]], dtype=torch.uint8)

In [21]:
torch.masked_select(c,mask)

tensor([ 255,  255,  255,  ...,    1,    1,    1], dtype=torch.uint8)

In [23]:
d=a.view(a.size(0)*a.size(1))

In [24]:
d.size()

torch.Size([921600])

In [25]:
e=c.view(c.size(0),c.size(1)*c.size(2))

In [26]:
e.size()

torch.Size([2, 921600])

In [27]:
mask=d.eq(255)

In [33]:
mask.long()

tensor([ 0,  0,  0,  ...,  0,  0,  0])

In [34]:
torch.index_select(e,1,mask.long())

tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 1,  1,  1,  ...,  1,  1,  1]], dtype=torch.uint8)

In [35]:
e

tensor([[   0,    0,    0,  ...,    0,    0,    0],
        [   1,    1,    1,  ...,    1,    1,    1]], dtype=torch.uint8)

In [38]:
torch.masked_select(e,mask)

tensor([ 255,  255,  255,  ...,    1,    1,    1], dtype=torch.uint8)

In [39]:
d==255

tensor([ 0,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)

In [46]:
indexes=(d==255).nonzero()

In [47]:
indexes.size()

torch.Size([4342, 1])

In [49]:
indexes.unique().size()

torch.Size([4342])

In [51]:
torch.index_select(e,1,indexes.squeeze())[:,1]

tensor([ 255,    1], dtype=torch.uint8)